# Generated by Django 5.0.8 on 2024-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', to='gallery.author'),
        ),
    ]
